// src/content/monsters/animals.js
// Beast-tagged creatures.
import { defineMonster } from '../define.js';
import {
  statusEffectOnHit,
  phaseOutOnDamaged,
  sandBurrowOnDamaged,
  corrodeEquipmentOnHit,
  typedDamageOnHit,
  burrowAndDieOnHit,
} from '../../rules/data/callbacks/combat.js';
import { selfThrowNearTargetOnSeen, fireBreathLineOnLOS, castSpellOnLOS } from '../../rules/data/callbacks/ai.js';
import { spawnPlasmaCloudOnDeath, centipedeSplitOnDeath, spawnFirePuffOnDeath } from '../../rules/data/callbacks/death.js';

defineMonster('rat', {
  name: 'Rat',
  glyph: 'r',
  color: '#b89070',
  glow: '#a06030',
  tags: ['beast', 'vermin', 'overworld'],
  tier: 0,
  intelligence: 2,
  packSense: true,
  packRadius: 4,
  hp: 6,
  hpPerLevel: 1,
  attack: 2,
  defense: 0,
  damageDice: '1d4',
  sizeClass: 'S',
  massKg: 2,
  resistances: { kinetic: { DR: 0 } },
  speed: 2,
  learnedSpellIds: ['rat_gnaw'],
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'rat_gnaw',
        abilityId: 'rat_gnaw',
        abilityName: 'Gnaw',
        minRange: 1,
        maxRange: 1,
        cooldownTurns: 6,
        chance: 0.4,
      }),
    ],
    onHit: [statusEffectOnHit(25, 0xdead0001, { key: "disease", turnsLeft: 20, potency: 1 }, "proc:diseased")],
  },
  specials: ["Disease 25%", "Gnaw (bleed)"],
  description: 'A mangy rodent with beady eyes.',
  corpseEat: { behavior: "scavenge", hpThreshold: 0.60, cooldownTurns: 5 },
});

defineMonster('boar', {
  name: 'Boar',
  glyph: 'b',
  color: '#9c6f3d',
  glow: '#5f3f20',
  tags: ['beast', 'overworld'],
  tier: 0,
  minDepth: 4,
  intelligence: 3,
  hp: 22,
  hpPerLevel: 1.2,
  attack: 2,
  defense: 1,
  damageDice: '1d6',
  sizeClass: 'M',
  massKg: 110,
  resistances: { kinetic: { DR: 2 } },
  speed: 2,
  learnedSpellIds: ['boar_charge', 'boar_bite'],
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'boar_charge',
        abilityId: 'boar_charge',
        abilityName: 'Charge',
        minRange: 2,
        maxRange: 5,
        cooldownTurns: 6,
        telegraphTurns: 1,
        chance: 0.65,
      }),
      castSpellOnLOS({
        spellId: 'boar_bite',
        abilityId: 'boar_bite',
        abilityName: 'Bite',
        minRange: 1,
        maxRange: 1,
        cooldownTurns: 4,
        chance: 0.55,
      }),
    ],
  },
  specials: ['Telegraphed charge (stuns)', 'Bite weakens (1 turn)'],
  description: 'A low-slung tusker that commits hard once it sights prey.',
  lootTable: 'drop:beast',
});

defineMonster('bat', {
  name: 'Bat',
  glyph: 'b',
  color: '#9080b0',
  glow: '#605080',
  tags: ['beast', 'vermin'],
  lootTable: 'drop:bat',
  tier: 0,
  canFly: true,
  intelligence: 2,
  aggro: 'passive',
  hp: 5,
  hpPerLevel: 0.5,
  attack: 0,
  defense: 0,
  damageDice: '1d2',
  sizeClass: 'XS',
  massKg: 1,
  resistances: { kinetic: { DR: 0 } },
  speed: 3,
  sleep: { pattern: "nocturnal", context: "roost", chance: 0.45 },
  learnedSpellIds: ['bat_shriek'],
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'bat_shriek',
        abilityId: 'bat_shriek',
        abilityName: 'Shriek',
        targeting: 'self',
        maxRange: 6,
        cooldownTurns: 8,
        telegraphTurns: 1,
        chance: 0.55,
      }),
    ],
  },
  specials: ["Telegraphed shriek"],
  description: 'A leathery-winged vermin that darts erratically.',
});

defineMonster('flaming_bat', {
  name: 'Flaming Bat',
  glyph: 'b',
  color: '#ff7a38',
  glow: '#b83f1d',
  tags: ['beast', 'vermin', 'fire', 'burning', 'glowing', 'rare'],
  lootTable: 'drop:bat',
  tier: 0,
  minDepth: 5,
  canFly: true,
  rare: true,
  intelligence: 3,
  hp: 8,
  hpPerLevel: 0.8,
  attack: 1,
  defense: 0,
  damageDice: '1d3',
  sizeClass: 'XS',
  massKg: 1,
  resistances: {
    kinetic: { DR: 0 },
    thermal: { igniteC: Infinity, burnMult: 0.35 },
  },
  speed: 3,
  hooks: {
    onHit: [
      typedDamageOnHit(2, {
        type: "fire",
        cause: "monster:flaming_bat:hit",
        emitEvent: "proc:flaming_bat:hit",
      }),
      statusEffectOnHit(35, 0xdead00fb, { key: "burn", turnsLeft: 2, potency: 1 }, "proc:burning"),
    ],
    onDeath: [
      spawnFirePuffOnDeath({ turnsLeft: 2, tickDamage: 1, radius: 0, identity: "flaming_bat_puff", name: "Bat Flame" }),
    ],
  },
  specials: ["Always burning", "Fire touch +2", "Burn 35%", "Death flame puff"],
  description: 'A screeching ember-wing that singes anything it claws before collapsing into cinders.',
});

defineMonster('grid_bug', {
  name: 'Grid Bug',
  glyph: '¤',
  color: '#bb66ff',
  glow: '#44ccff',
  tags: ['beast', 'vermin', 'electric'],
  goreType: 'spark',
  tier: 0,
  intelligence: 1,
  hp: 5,
  hpPerLevel: 0.5,
  attack: 0,
  defense: 0,
  damageDice: '1d2',
  sizeClass: 'XS',
  massKg: 1,
  resistances: { kinetic: { DR: 0 }, electric: { ohms: Infinity } },
  speed: 1,
  hooks: {
    onHit: [statusEffectOnHit(30, 0xdead0010, { key: "shock", turnsLeft: 2, potency: 1 }, "proc:shocked")],
    onDeath: [spawnPlasmaCloudOnDeath({ turnsLeft: 6, radius: 1, damage: 2 })],
  },
  specials: ["Shock 30%"],
  description: 'A tiny crackling insect that moves only along the grid axes.',
});

defineMonster('cave_snake', {
  name: 'Cave Snake',
  glyph: 'S',
  color: '#88aa66',
  glow: '#667744',
  tags: ['beast'],
  tier: 0,
  intelligence: 2,
  aggro: 'passive',
  hp: 8,
  hpPerLevel: 1,
  attack: 0,
  defense: 0,
  damageDice: '1d2',
  sizeClass: 'XS',
  massKg: 2,
  resistances: { kinetic: { DR: 0 } },
  speed: 3,
  hooks: null,
  specials: [],
  description: 'A small, harmless serpent that slithers through the dark.',
  lootTable: 'drop:snake',
});

defineMonster('cave_spider', {
  name: 'Cave Spider',
  glyph: 'x',
  color: '#88bb88',
  glow: '#558855',
  tags: ['beast'],
  tier: 0,
  minDepth: 2,
  intelligence: 3,
  packSense: true,
  packRadius: 5,
  hp: 10,
  hpPerLevel: 1,
  attack: 0,
  defense: 0,
  damageDice: '1d3',
  sizeClass: 'S',
  massKg: 8,
  resistances: { kinetic: { DR: 0 } },
  speed: 2,
  learnedSpellIds: ['web_spit', 'spider_lunge'],
  hooks: {
    onSeen: [selfThrowNearTargetOnSeen({ searchRadius: 1, fallbackSearchRadius: 2, cooldownTurns: 3, chance: 0.25 })],
    whileLOS: [
      castSpellOnLOS({
        spellId: 'spider_lunge',
        abilityId: 'spider_lunge',
        abilityName: 'Lunge',
        minRange: 1,
        maxRange: 1,
        cooldownTurns: 5,
        chance: 0.4,
      }),
      castSpellOnLOS({
        spellId: 'web_spit',
        abilityId: 'web_spit',
        abilityName: 'Web Spit',
        minRange: 2,
        maxRange: 6,
        cooldownTurns: 6,
        chance: 0.45,
      }),
    ],
  },
  specials: ["Throws web (25%)", "Web spit", "Lunge (stagger)"],
  description: 'A skittish arachnid. It spins webs but lacks venom.',
  lootTable: 'drop:spider',
});

defineMonster('snake', {
  name: 'Snake',
  glyph: 'S',
  color: '#55aa44',
  glow: '#338822',
  tags: ['beast', 'venomous', 'overworld'],
  tier: 0,
  minDepth: 2,
  intelligence: 2,
  aggro: 'passive',
  hp: 10,
  hpPerLevel: 1,
  attack: 0,
  defense: 0,
  damageDice: '1d3',
  sizeClass: 'XS',
  massKg: 3,
  resistances: { kinetic: { DR: 0 }, chemical: { toxMult: 0 } },
  speed: 3,
  learnedSpellIds: ['snake_fang'],
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'snake_fang',
        abilityId: 'snake_fang',
        abilityName: 'Fang Strike',
        minRange: 1,
        maxRange: 1,
        cooldownTurns: 6,
        chance: 0.45,
      }),
    ],
    onHit: [statusEffectOnHit(25, 0xdead000f, { key: "poison", turnsLeft: 5, potency: 1 }, "proc:poisoned")],
  },
  specials: ["Poison 25%", "Fang Strike"],
  description: 'A hissing serpent with venomous fangs.',
});

defineMonster('pit_viper', {
  name: 'Pit Viper',
  glyph: 'S',
  color: '#44dd44',
  glow: '#22aa22',
  tags: ['beast', 'venomous', 'venom_glowing', 'rare'],
  tier: 0,
  minDepth: 4,
  rare: true,
  intelligence: 2,
  hp: 30,
  hpPerLevel: 1.5,
  attack: 2,
  defense: 0,
  damageDice: '1d4',
  sizeClass: 'XS',
  massKg: 4,
  resistances: { kinetic: { DR: 0 }, chemical: { toxMult: 0 } },
  speed: 3,
  hooks: {
    onHit: [statusEffectOnHit(30, 0xdead0010, { key: "poison", turnsLeft: 4, potency: 1 }, "proc:poisoned")],
  },
  specials: ["Poison 30%"],
  description: 'A thick-bodied serpent with iridescent scales. Its bite delivers a potent venom.',
  lootTable: 'drop:pit_viper',
});

defineMonster('cave_bear', {
  name: 'Cave Bear',
  glyph: 'B',
  color: '#8b6040',
  glow: '#5a3a20',
  tags: ['beast', 'rare', 'overworld', 'climbing'],
  tier: 0,
  minDepth: 5,
  intelligence: 3,
  hp: 42,
  hpPerLevel: 2,
  attack: 4,
  defense: 2,
  damageDice: '2d6',
  sizeClass: 'L',
  massKg: 350,
  resistances: { kinetic: { DR: 3 } },
  speed: 1,
  sleep: { pattern: "diurnal", context: "den" },
  hooks: {
    onHit: [statusEffectOnHit(30, 0xdead0200, { key: "stun", turnsLeft: 2, potency: 1 }, "proc:stunned")],
  },
  specials: ["Stun 30%"],
  description: 'A massive bear with matted fur and scarred hide. Its claws can split stone.',
  lootTable: 'drop:cave_bear',
});

defineMonster('dragon_whelp', {
  name: 'Dragon Whelp',
  glyph: 'D',
  color: '#ff8a2b',
  glow: '#ff5a12',
  tags: ['beast', 'draconic', 'rare', 'glowing'],
  tier: 0,
  minDepth: 5,
  canFly: true,
  rare: true,
  intelligence: 6,
  visionRange: 9,
  retreatHpPct: 0.20,
  hp: 36,
  hpPerLevel: 2.5,
  attack: 4,
  defense: 3,
  damageDice: '1d8',
  sizeClass: 'L',
  massKg: 240,
  resistances: {
    kinetic: { DR: 5, pierceMult: 0.85 },
    thermal: { igniteC: Infinity, burnMult: 0 },
  },
  speed: 2,
  hooks: {
    whileLOS: [fireBreathLineOnLOS({
      minRange: 2,
      maxRange: 6,
      cooldownTurns: 6,
      damage: 4,
      hazardDamage: 1,
      hazardTurns: 3,
      burnTurns: 3,
      burnPotency: 2,
    })],
    onHit: [statusEffectOnHit(20, 0xdead0201, { key: "burn", turnsLeft: 3, potency: 2 }, "proc:burning")],
  },
  specials: ["Fire breath", "Burn 20%"],
  description: 'A juvenile dragon whose breath already runs hotter than a forge. Even its scales throw heat into the dark.',
  lootTable: 'drop:dragon_whelp',
});

defineMonster('dire_wolf', {
  name: 'Dire Wolf',
  glyph: 'd',
  color: '#909f76',
  glow: '#5b6947',
  tags: ['beast'],
  tier: 1,
  intelligence: 4,
  packSense: true,
  packRadius: 6,
  hp: 22,
  hpPerLevel: 2.0,
  attack: 4,
  defense: 1,
  damageDice: '2d4',
  sizeClass: 'M',
  massKg: 92,
  resistances: { kinetic: { DR: 2 } },
  speed: 3,
  learnedSpellIds: ['wolf_howl'],
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'wolf_howl',
        abilityId: 'wolf_howl',
        abilityName: 'Howl',
        targeting: 'self',
        maxRange: 7,
        cooldownTurns: 10,
        telegraphTurns: 1,
        chance: 0.6,
      }),
    ],
    onHit: [statusEffectOnHit(20, 0xdead5101, { key: "bleed", turnsLeft: 2, potency: 1 }, "proc:bleeding")],
  },
  specials: ['Telegraphed howl', 'Bleed 20%'],
  description: 'A scarred pack alpha whose howl snaps nearby hunters into formation.',
  lootTable: 'drop:beast',
});

defineMonster('acid_spitter', {
  name: 'Acid Spitter',
  glyph: 'a',
  color: '#b8d95a',
  glow: '#6f8e2a',
  tags: ['beast', 'acid', 'ranged'],
  tier: 1,
  minDepth: 7,
  intelligence: 5,
  hp: 22,
  hpPerLevel: 1.7,
  attack: 2,
  defense: 1,
  damageDice: '1d6',
  sizeClass: 'M',
  massKg: 52,
  resistances: {
    kinetic: { DR: 1 },
    chemical: { toxMult: 0.5 },
  },
  speed: 2,
  learnedSpellIds: ['acid_spit'],
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'acid_spit',
        abilityId: 'acid_spit',
        abilityName: 'Acid Spit',
        minRange: 2,
        maxRange: 7,
        cooldownTurns: 7,
        telegraphTurns: 1,
        chance: 0.65,
      }),
    ],
  },
  specials: ['Telegraphed acid spit', 'Weakens on hit', 'Leaves acid pool'],
  description: 'A bloated crawler that hawks sizzling bile across the room.',
  lootTable: 'drop:beast',
});

defineMonster('phase_spider', {
  name: 'Phase Spider',
  glyph: 'x',
  color: '#aa66dd',
  glow: '#7733aa',
  tags: ['beast', 'venomous'],
  tier: 1,
  minDepth: 9,
  intelligence: 5,
  packSense: true,
  packRadius: 6,
  hp: 22,
  hpPerLevel: 1.5,
  attack: 2,
  defense: 1,
  damageDice: '1d6',
  sizeClass: 'M',
  massKg: 40,
  resistances: { kinetic: { DR: 3 }, chemical: { toxMult: 0 } },
  speed: 2,
  hooks: {
    onSeen: [selfThrowNearTargetOnSeen({ searchRadius: 1, fallbackSearchRadius: 5, cooldownTurns: 4, chance: 0.2 })],
    onHit: [statusEffectOnHit(30, 0xdead0404, { key: "poison", turnsLeft: 1, potency: 1 }, "proc:poisoned")],
    onDamaged: [phaseOutOnDamaged(20, 0xdead0405)],
  },
  specials: ["Phase teleport (50%)", "Poison 30%", "Phase out 20%"],
  description: 'A shimmering spider that blinks in and out of existence, striking from impossible angles.',
  lootTable: 'drop:spider',
});

defineMonster('spider', {
  name: 'Spider',
  glyph: 'x',
  color: '#55bb55',
  glow: '#338833',
  tags: ['beast', 'venomous'],
  tier: 0,
  minDepth: 2,
  intelligence: 3,
  packSense: true,
  packRadius: 6,
  hp: 14,
  hpPerLevel: 1.2,
  attack: 1,
  defense: 0,
  damageDice: '1d4',
  sizeClass: 'S',
  massKg: 15,
  resistances: { kinetic: { DR: 0 }, chemical: { toxMult: 0 } },
  speed: 3,
  learnedSpellIds: ['web_spit'],
  hooks: {
    onSeen: [selfThrowNearTargetOnSeen({ searchRadius: 1, fallbackSearchRadius: 2, cooldownTurns: 3, chance: 0.25 })],
    whileLOS: [
      castSpellOnLOS({
        spellId: 'web_spit',
        abilityId: 'web_spit',
        abilityName: 'Web Spit',
        minRange: 2,
        maxRange: 6,
        cooldownTurns: 6,
        chance: 0.45,
      }),
    ],
    onHit: [statusEffectOnHit(15, 0xdead0002, { key: "poison", turnsLeft: 3, potency: 1 }, "proc:poisoned")],
  },
  specials: ["Web spit", "Poison 15%"],
  description: 'A dog-sized arachnid with venomous fangs.',
  lootTable: 'drop:spider',
});

defineMonster('dragon', {
  name: 'Dragon',
  glyph: 'D',
  color: '#ffcc33',
  glow: '#dd9900',
  tags: ['beast', 'draconic'],
  tier: 3,
  canFly: true,
  intelligence: 8,
  retreatHpPct: 0.15,
  polymorphResistance: 0.65,
  polymorphStability: 2,
  polymorphFailureMode: 'resist',
  hp: 40,
  hpPerLevel: 5,
  attack: 8,
  defense: 6,
  damageDice: '3d8',
  sizeClass: 'XL',
  massKg: 800,
  resistances: {
    kinetic: { DR: 10, pierceMult: 0.7 },
    thermal: { igniteC: Infinity, burnMult: 0 },
  },
  speed: 2,
  sleep: "ancient",
  hooks: {
    onHit: [statusEffectOnHit(20, 0xdead0004, { key: "burn", turnsLeft: 5, potency: 4 }, "proc:burning")],
  },
  specials: ["Burn 20%", "Resists polymorph"],
  description: 'Scales like hammered bronze. The apex predator of the deep.',
  lootTable: 'drop:dragon',
});

defineMonster('cockatrice', {
  name: 'Cockatrice',
  glyph: 'c',
  color: '#b0b898',
  glow: '#787f68',
  tags: ['beast'],
  tier: 0,
  minDepth: 4,
  intelligence: 2,
  aggro: 'passive',
  polymorphResistance: 0.4,
  polymorphStability: 2,
  polymorphFailureMode: 'resist',
  hp: 14,
  hpPerLevel: 1,
  attack: 0,
  defense: 0,
  damageDice: '1d3',
  sizeClass: 'S',
  massKg: 12,
  resistances: { kinetic: { DR: 0 }, chemical: { toxMult: 0 } },
  speed: 2,
  hooks: {
    onHit: [
      statusEffectOnHit(80, 0xdead0080, { key: "slowed", turnsLeft: 6, potency: 2 }, "proc:slowed"),
      statusEffectOnHit(60, 0xdead0081, { key: "confuse", turnsLeft: 5, potency: 1 }, "proc:confused"),
      statusEffectOnHit(40, 0xdead0082, { key: "weakened", turnsLeft: 5, potency: 1 }, "proc:weakened"),
    ],
  },
  specials: ["Petrifying touch (slow 80%)", "Confuse 60%", "Weaken 40%", "Passive", "Stone-anchored polymorph resistance"],
  description: 'A scaly hen-lizard with dead white eyes. Its touch numbs flesh to stone.',
  lootTable: 'drop:cockatrice',
});

defineMonster('rust_monster', {
  name: 'Rust Monster',
  glyph: 'R',
  color: '#cc7744',
  glow: '#884422',
  tags: ['beast', 'aberration'],
  tier: 0,
  minDepth: 4,
  intelligence: 3,
  aggro: 'passive',
  hp: 14,
  hpPerLevel: 1.5,
  attack: 1,
  defense: 1,
  damageDice: '1d4',
  sizeClass: 'M',
  massKg: 100,
  resistances: { kinetic: { DR: 4 }, chemical: { toxMult: 0 } },
  speed: 2,
  hooks: {
    onHit: [corrodeEquipmentOnHit(40, 0xdead0040)],
  },
  specials: ["Corrodes metal equipment"],
  description: 'A rust-brown beetle whose feathery antennae dissolve metal on contact.',
});

defineMonster('wild_elk', {
  name: 'Wild Elk',
  glyph: 'E',
  color: '#c8a870',
  glow: '#8a6840',
  tags: ['beast', 'herbivore', 'overworld'],
  tier: 0,
  intelligence: 1,
  aggro: 'passive',
  hp: 32,
  hpPerLevel: 2,
  attack: 2,
  defense: 1,
  damageDice: '1d8',
  sizeClass: 'L',
  massKg: 400,
  resistances: { kinetic: { DR: 2 } },
  speed: 2,
  hooks: {
    onHit: [statusEffectOnHit(25, 0xdead0701, { key: "stun", turnsLeft: 1, potency: 1 }, "proc:stunned")],
  },
  specials: ["Passive (attacks if hit)", "Stun hooves 25%"],
  description: 'A large cervid with branching antlers. Peaceful unless threatened.',
});

defineMonster('giant_frog', {
  name: 'Giant Frog',
  glyph: 'F',
  color: '#44bb33',
  glow: '#228811',
  tags: ['beast', 'amphibian', 'overworld'],
  tier: 0,
  intelligence: 1,
  hp: 18,
  hpPerLevel: 1.5,
  attack: 2,
  defense: 0,
  damageDice: '1d6',
  sizeClass: 'M',
  massKg: 50,
  resistances: { kinetic: { DR: 0 }, chemical: { toxMult: 0.5 } },
  speed: 2,
  learnedSpellIds: ['poison_spit'],
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'poison_spit',
        abilityId: 'poison_spit',
        abilityName: 'Poison Spit',
        minRange: 2,
        maxRange: 5,
        cooldownTurns: 5,
        chance: 0.4,
      }),
    ],
  },
  specials: ["Poison Spit (ranged)", "Toxin-resistant"],
  description: 'A bloated amphibian with venomous saliva.',
});

defineMonster('sand_crab', {
  name: 'Sand Crab',
  glyph: 'c',
  color: '#d4a060',
  glow: '#a07038',
  tags: ['beast', 'crustacean', 'overworld'],
  tier: 0,
  intelligence: 1,
  hp: 14,
  hpPerLevel: 1.2,
  attack: 2,
  defense: 2,
  damageDice: '1d4',
  sizeClass: 'S',
  massKg: 6,
  resistances: {
    kinetic: { DR: 2, bluntMult: 1.2, pierceMult: 0.8, slashMult: 0.9 },
    chemical: { toxMult: 0.7 },
  },
  speed: 2,
  hooks: {
    onDamaged: [sandBurrowOnDamaged(45, 0xdead0710)],
  },
  specials: ["Shells up when damaged"],
  description: 'A shovel-clawed shore crab that digs in under pressure.',
});

defineMonster('mountain_goat', {
  name: 'Mountain Goat',
  glyph: 'G',
  color: '#c8c8cc',
  glow: '#888898',
  tags: ['beast', 'herbivore', 'overworld', 'climbing'],
  tier: 0,
  intelligence: 1,
  hp: 16,
  hpPerLevel: 1.2,
  attack: 1,
  defense: 0,
  damageDice: '1d4',
  sizeClass: 'M',
  massKg: 90,
  resistances: { kinetic: { DR: 2 } },
  speed: 2,
  evade: 3,
  specials: ["High evasion"],
  description: 'A sure-footed climber with sharp horns.',
});

defineMonster('stag_beetle', {
  name: 'Stag Beetle',
  glyph: 'b',
  color: '#3a3020',
  glow: '#1e1a10',
  tags: ['beast', 'insect', 'overworld'],
  tier: 0,
  intelligence: 1,
  hp: 8,
  hpPerLevel: 1,
  attack: 2,
  defense: 0,
  damageDice: '1d3',
  sizeClass: 'S',
  massKg: 3,
  resistances: { kinetic: { DR: 1 } },
  speed: 2,
  hooks: {
    onHit: [statusEffectOnHit(35, 0xdead0702, { key: "stun", turnsLeft: 1, potency: 1 }, "proc:stunned")],
  },
  specials: ["Paralytic bite 35%"],
  description: 'An armored insect with impressive mandibles.',
});

defineMonster('heron', {
  name: 'Heron',
  glyph: 'h',
  color: '#8ab0cc',
  glow: '#507888',
  tags: ['beast', 'bird', 'rare', 'overworld'],
  tier: 0,
  rare: true,
  canFly: true,
  intelligence: 2,
  retreatHpPct: 0.50,
  hp: 14,
  hpPerLevel: 1,
  attack: 2,
  defense: 0,
  damageDice: '1d4',
  sizeClass: 'M',
  massKg: 4,
  resistances: { kinetic: { DR: 0 } },
  speed: 3,
  specials: ["Flies away when wounded"],
  description: 'A long-legged wading bird that flees at first hurt.',
});

defineMonster('killer_bee', {
  name: 'Killer Bee',
  glyph: 'a',
  color: '#e8cc30',
  glow: '#b89a10',
  tags: ['beast', 'vermin'],
  tier: 0,
  minDepth: 2,
  canFly: true,
  intelligence: 2,
  packSense: true,
  packRadius: 8,
  hp: 5,
  hpPerLevel: 0.5,
  attack: 0,
  defense: 0,
  damageDice: '1d2',
  sizeClass: 'XS',
  massKg: 1,
  resistances: { kinetic: { DR: 0 }, chemical: { toxMult: 0 } },
  speed: 3,
  hooks: {
    onHit: [statusEffectOnHit(20, 0xdead0060, { key: "poison", turnsLeft: 4, potency: 1 }, "proc:poisoned")],
  },
  specials: ["Poison sting 20%", "Flying", "Large swarm radius"],
  description: 'A fat-bodied insect that attacks in angry clouds. One sting is nothing — twenty is a funeral.',
});

defineMonster('rot_grub', {
  name: 'Rot Grub',
  glyph: 'µ',
  color: '#d4a0a0',
  glow: '#aa6060',
  tags: ['beast', 'vermin'],
  tier: 0,
  minDepth: 2,
  intelligence: 1,
  hp: 2,
  hpPerLevel: 0.3,
  attack: 0,
  defense: 0,
  damageDice: '1d1',
  sizeClass: 'XS',
  massKg: 0.5,
  resistances: { kinetic: { DR: 0 } },
  speed: 3,
  hooks: {
    onSeen: [selfThrowNearTargetOnSeen({ searchRadius: 1, fallbackSearchRadius: 2, cooldownTurns: 0, chance: 0.70 })],
    onHit: [
      burrowAndDieOnHit(80, 0xdead0090, { key: "bleed", turnsLeft: 8, potency: 2 }, "proc:rot_grub:burrow"),
    ],
  },
  specials: ["Leaps at you on sight", "Burrows in and disappears (heavy bleed 80%)"],
  description: 'A writhing pale grub no bigger than a finger. It burrows under the skin on contact.',
});

defineMonster('centipede', {
  name: 'Giant Centipede',
  glyph: 'c',
  color: '#cc7744',
  glow: '#884422',
  tags: ['beast', 'vermin', 'long-creature'],
  disabled: true,
  tier: 0,
  intelligence: 2,
  hp: 4,
  hpPerLevel: 0.5,
  attack: 0,
  defense: 0,
  damageDice: '1d3',
  sizeClass: 'S',
  massKg: 5,
  resistances: { kinetic: { DR: 1 } },
  speed: 3,
  segmentCount: { min: 4, max: 7 },
  hooks: {
    onHit: [statusEffectOnHit(20, 0xdead0500, { key: "poison", turnsLeft: 3, potency: 1 }, "proc:poisoned")],
    onDeath: [centipedeSplitOnDeath()],
  },
  specials: ["Poison 20%", "Multi-segment"],
  description: 'A writhing arthropod that moves as one. Cut it and both halves keep going.',
});
