// Aura-bearing creatures. Their abilities are authored as ordinary self-cast
// spells so the AI, hazard lifetime, and presentation all share one path.
import { defineMonster } from '../define.js';
import { castSpellOnLOS } from '../../rules/data/callbacks/ai.js';

defineMonster('plaguebearer', {
  name: 'Plaguebearer',
  glyph: 'P',
  color: '#9ac46b',
  glow: '#587936',
  tags: ['undead', 'caster', 'plague'],
  tier: 2,
  minDepth: 11,
  intelligence: 8,
  hp: 28,
  hpPerLevel: 2.2,
  attack: 3,
  defense: 2,
  damageDice: '1d6',
  sizeClass: 'M',
  massKg: 68,
  resistances: { kinetic: { DR: 2 }, chemical: { toxMult: 0.2 } },
  speed: 1,
  maxMana: 30,
  manaRegen: 0.1,
  learnedSpellIds: ['plaguebearer_aura'],
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'plaguebearer_aura',
        abilityId: 'plaguebearer_aura',
        abilityName: 'Miasma',
        targeting: 'self',
        maxRange: 8,
        cooldownTurns: 8,
        telegraphTurns: 1,
        chance: 0.65,
      }),
    ],
  },
  specials: ['Poison aura', 'Toxic resistance'],
  description: 'A swollen corpse whose breath carries a living sickness.',
  lootTable: 'drop:undead',
});

defineMonster('war_drummer', {
  name: 'War Drummer',
  glyph: 'D',
  color: '#d89b55',
  glow: '#8c5127',
  tags: ['humanoid', 'martial', 'support'],
  tier: 1,
  minDepth: 8,
  intelligence: 7,
  packSense: true,
  packRadius: 6,
  hp: 26,
  hpPerLevel: 2,
  attack: 4,
  defense: 1,
  damageDice: '1d8',
  sizeClass: 'M',
  massKg: 82,
  resistances: { kinetic: { DR: 1 } },
  speed: 2,
  maxMana: 24,
  manaRegen: 0.1,
  wielding: ['iron_mace'],
  learnedSpellIds: ['war_drum'],
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'war_drum',
        abilityId: 'war_drum',
        abilityName: 'War Drum',
        targeting: 'self',
        maxRange: 8,
        cooldownTurns: 8,
        telegraphTurns: 1,
        chance: 0.7,
      }),
    ],
  },
  specials: ['Allied haste aura', 'Pack fighter'],
  description: 'A scarred battlefield drummer who turns every nearby footfall into a charge.',
  lootTable: 'drop:humanoid',
});

defineMonster('dread_warden', {
  name: 'Dread Warden',
  glyph: 'W',
  color: '#9b78c7',
  glow: '#513b72',
  tags: ['undead', 'caster', 'guardian'],
  tier: 2,
  minDepth: 12,
  intelligence: 8,
  hp: 34,
  hpPerLevel: 2.5,
  attack: 4,
  defense: 4,
  damageDice: '1d8',
  sizeClass: 'M',
  massKg: 90,
  resistances: { kinetic: { DR: 3 }, shadow: { DR: 2 } },
  speed: 1,
  maxMana: 32,
  manaRegen: 0.1,
  learnedSpellIds: ['dread_warden_aura'],
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'dread_warden_aura',
        abilityId: 'dread_warden_aura',
        abilityName: 'Dread Ward',
        targeting: 'self',
        maxRange: 8,
        cooldownTurns: 9,
        telegraphTurns: 1,
        chance: 0.6,
      }),
    ],
  },
  specials: ['Fear aura', 'Armored guardian'],
  description: 'A grave sentinel whose silence is filled by the panic of the living.',
  lootTable: 'drop:undead',
});

defineMonster('void_priest', {
  name: 'Void Priest',
  glyph: 'V',
  color: '#8374d8',
  glow: '#3d347f',
  tags: ['humanoid', 'caster', 'void'],
  tier: 3,
  minDepth: 16,
  intelligence: 10,
  hp: 32,
  hpPerLevel: 2.3,
  attack: 3,
  defense: 2,
  damageDice: '1d6',
  sizeClass: 'M',
  massKg: 70,
  resistances: { arcane: { DR: 3 }, shadow: { DR: 3 } },
  speed: 1,
  maxMana: 48,
  manaRegen: 0.2,
  learnedSpellIds: ['void_priest_aura'],
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'void_priest_aura',
        abilityId: 'void_priest_aura',
        abilityName: 'Null Field',
        targeting: 'self',
        maxRange: 9,
        cooldownTurns: 9,
        telegraphTurns: 1,
        chance: 0.65,
      }),
    ],
  },
  specials: ['Silence aura', 'Void resistance'],
  description: 'A hollow-eyed celebrant who makes magic fail simply by standing near it.',
  lootTable: 'drop:caster',
});

defineMonster('blood_herald', {
  name: 'Blood Herald',
  glyph: 'H',
  color: '#cc5967',
  glow: '#7c2638',
  tags: ['undead', 'caster', 'blood'],
  tier: 3,
  minDepth: 16,
  intelligence: 9,
  hp: 38,
  hpPerLevel: 2.8,
  attack: 5,
  defense: 3,
  damageDice: '1d8',
  sizeClass: 'M',
  massKg: 84,
  resistances: { kinetic: { DR: 2 }, shadow: { DR: 2 } },
  speed: 2,
  maxMana: 42,
  manaRegen: 0.15,
  learnedSpellIds: ['blood_herald_aura'],
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'blood_herald_aura',
        abilityId: 'blood_herald_aura',
        abilityName: 'Blood Call',
        targeting: 'self',
        maxRange: 9,
        cooldownTurns: 9,
        telegraphTurns: 1,
        chance: 0.65,
      }),
    ],
  },
  specials: ['Wounded-allies berserk aura', 'Blood magic'],
  description: 'A crimson standard-bearer who makes every wound in its cohort answer with rage.',
  lootTable: 'drop:undead',
});
