// src/content/monsters/humanoids.js
// Humanoid, giant, and demon creatures.
import { defineMonster } from '../define.js';
import {
  statusEffectOnHit,
  selfBuffOnHit,
  bonusDamageOnBeforeHit,
  retaliateOnDamaged,
  phaseOutOnDamaged,
  healOnDamaged,
  spillLootAndShortBlinkOnDamaged,
  stealAndBlinkOnHit,
} from '../../rules/data/callbacks/combat.js';
import { castSpellOnLOS } from '../../rules/data/callbacks/ai.js';

defineMonster('goblin', {
  name: 'Goblin',
  glyph: 'g',
  color: '#7ecc5a',
  glow: '#4a9030',
  tags: ['humanoid'],
  tier: 0,
  minDepth: 2,
  intelligence: 4,
  packSense: true,
  packRadius: 5,
  hp: 12,
  hpPerLevel: 1.5,
  attack: 3,
  defense: 0,
  damageDice: '1d6',
  sizeClass: 'S',
  massKg: 30,
  resistances: { kinetic: { DR: 0 } },
  speed: 2,
  wielding: [
    "goblin_jagged_shiv",
    "goblin_jagged_shiv",
    "goblin_jagged_shiv",
    "goblin_jagged_shiv",
    "goblin_shiv",
  ],
  equipped: ["leather_armor", "scout_hood"],
  learnedSpellIds: ['goblin_dirty_trick'],
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'goblin_dirty_trick',
        abilityId: 'goblin_dirty_trick',
        abilityName: 'Dirty Trick',
        minRange: 1,
        maxRange: 1,
        cooldownTurns: 7,
        telegraphTurns: 1,
        chance: 0.35,
      }),
    ],
  },
  specials: ["Wields a shiv (often jagged)", "Dirty Trick (blind)", "May spawn lightly armored"],
  description: 'A sneering green-skinned runt armed with a rusty dagger.',
  lootTable: 'drop:goblin',
  corpseEat: { behavior: "scavenge", hpThreshold: 0.70, cooldownTurns: 5 },
});

defineMonster('goblin_archer', {
  name: 'Goblin Archer',
  glyph: 'g',
  color: '#5eaa3a',
  glow: '#3a7020',
  tags: ['humanoid'],
  tier: 0,
  minDepth: 3,
  intelligence: 4,
  packSense: true,
  packRadius: 5,
  hp: 10,
  hpPerLevel: 1,
  attack: 3,
  defense: 0,
  damageDice: '1d6',
  sizeClass: 'S',
  massKg: 30,
  resistances: { kinetic: { DR: 0 } },
  speed: 2,
  equipped: [
    "goblin_barbed_shortbow",
    "bow_short",
    "ammo_arrows",
  ],
  hooks: null,
  specials: ["May spawn with barbed bow"],
  description: 'A goblin with a crude shortbow and a quiver of bent arrows.',
  lootTable: 'drop:goblin',
});

defineMonster('loot_goblin', {
  name: 'Loot Goblin',
  glyph: 'g',
  color: '#f4d46a',
  glow: '#b88b23',
  tags: ['humanoid', 'rare'],
  tier: 0,
  rare: true,
  intelligence: 9,
  visionRange: 3,
  retreatHpPct: 2.0,
  hp: 64,
  hpPerLevel: 3.0,
  attack: 1,
  defense: 2,
  damageDice: '1d3',
  sizeClass: 'S',
  massKg: 28,
  resistances: { kinetic: { DR: 2 } },
  speed: 3,
  hooks: {
    onDamaged: [
      spillLootAndShortBlinkOnDamaged({
        dropTable: 'hit:loot_goblin',
        dropChancePct: 100,
        dropCooldownTurns: 0,
        blinkChancePct: 65,
        blinkCooldownTurns: 2,
        blinkDistance: 4,
        seedSalt: 0xdead00b0,
      }),
    ],
  },
  specials: ['Always retreats', 'Short panic blink', 'Drops treasure when hit'],
  description: 'A jittery, overstuffed goblin that bolts at first contact, blinking only a few tiles before spilling more treasure.',
  lootTable: 'drop:loot_goblin',
});

defineMonster('bandit', {
  name: 'Bandit',
  glyph: 'b',
  color: '#c9b08c',
  glow: '#7b6547',
  tags: ['humanoid'],
  tier: 0,
  minDepth: 4,
  intelligence: 5,
  packSense: true,
  packRadius: 5,
  hp: 16,
  hpPerLevel: 1.3,
  attack: 3,
  defense: 1,
  damageDice: '1d6',
  sizeClass: 'M',
  massKg: 78,
  resistances: { kinetic: { DR: 1 } },
  speed: 2,
  wielding: [
    'dagger_quick',
    'dagger_quick',
    'goblin_shiv',
  ],
  equipped: ["leather_armor", "scout_hood"],
  hooks: null,
  specials: ['Weapon user (dagger/shiv)', 'May spawn with light armor'],
  description: 'A cutthroat drifter with a cheap blade and a hungry stare.',
  lootTable: 'drop:goblin',
});

defineMonster('bandit_archer', {
  name: 'Bandit Archer',
  glyph: 'b',
  color: '#b2c6d9',
  glow: '#677f97',
  tags: ['humanoid'],
  tier: 0,
  minDepth: 4,
  intelligence: 6,
  packSense: true,
  packRadius: 5,
  hp: 14,
  hpPerLevel: 1.1,
  attack: 3,
  defense: 0,
  damageDice: '1d6',
  sizeClass: 'M',
  massKg: 74,
  resistances: { kinetic: { DR: 0 } },
  speed: 2,
  equipped: [
    "bow_short",
    { slot: 'ammo', itemId: 'ammo_arrows' },
  ],
  hooks: null,
  specials: ['Ranged weapon user (shortbow)'],
  description: 'A highway bowman who peppers lanes before closing in.',
  lootTable: 'drop:goblin',
});

defineMonster('bandit_captain', {
  name: 'Bandit Captain',
  glyph: 'b',
  color: '#d9c57a',
  glow: '#8e6f2f',
  tags: ['humanoid', 'elite'],
  tier: 1,
  minDepth: 8,
  intelligence: 7,
  packSense: true,
  packRadius: 5,
  hp: 34,
  hpPerLevel: 2.1,
  attack: 3,
  defense: 2,
  damageDice: '1d8',
  sizeClass: 'M',
  massKg: 88,
  resistances: { kinetic: { DR: 3 } },
  speed: 2,
  learnedSpellIds: ['shield_bash'],
  wielding: ['iron_mace', 'dagger_quick', 'sword_plain'],
  equipped: [
    "shield_wood", "shield_iron",
    "chain_armor",
    "helm_iron", "helm_steel",
    "boots_leather", "belt_leather",
  ],
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'shield_bash',
        abilityId: 'shield_bash',
        abilityName: 'Shield Bash',
        minRange: 1,
        maxRange: 1,
        cooldownTurns: 6,
        telegraphTurns: 1,
        chance: 0.7,
      }),
    ],
  },
  specials: ['Telegraphed shield bash', 'Weapon + shield'],
  description: 'A disciplined raider who opens duels by smashing foes off-balance.',
  lootTable: 'drop:goblin',
});

defineMonster('orc', {
  name: 'Orc',
  glyph: 'o',
  color: '#cc6644',
  glow: '#993320',
  tags: ['humanoid'],
  tier: 1,
  intelligence: 5,
  packSense: true,
  packRadius: 5,
  hp: 20,
  hpPerLevel: 2,
  attack: 4,
  defense: 1,
  damageDice: '1d8',
  sizeClass: 'M',
  massKg: 95,
  resistances: { kinetic: { DR: 2 } },
  speed: 2,
  wielding: [
    'axe_heavy', 'axe_heavy', 'axe_heavy',
    'sword_plain', 'sword_plain',
    'iron_mace',
  ],
  equipped: [
    "leather_armor", "chain_armor",
    "helm_iron", "boots_leather",
  ],
  hooks: {
    onBeforeHit: [bonusDamageOnBeforeHit(25, 0xdead0007, 2, "proc:rage")],
  },
  specials: ["Rage +2 dmg (25%)", "Armed and armored"],
  description: 'A thick-skulled brute with a chipped cleaver.',
  lootTable: 'drop:orc',
});

defineMonster('orc_shaman', {
  name: 'Orc Shaman',
  glyph: 'o',
  color: '#88bbdd',
  glow: '#557799',
  tags: ['humanoid', 'caster', 'witchy'],
  tier: 1,
  minDepth: 8,
  intelligence: 8,
  visionRange: 9,
  retreatHpPct: 0.30,
  packSense: true,
  packRadius: 5,
  hp: 20,
  hpPerLevel: 1.5,
  attack: 2,
  defense: 1,
  damageDice: '1d6',
  sizeClass: 'M',
  massKg: 90,
  resistances: { kinetic: { DR: 2 } },
  speed: 2,
  wielding: ['staff_oak'],
  equipped: ["leather_armor", "sandals_hemp"],
  learnedSpellIds: ['frost', 'heal'],
  maxMana: 30,
  manaRegen: 0.16,
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'heal',
        targeting: 'self',
        cooldownTurns: 15,
        chance: 0.40,
      }),
      castSpellOnLOS({
        spellId: 'frost',
        minRange: 2,
        maxRange: 9,
        cooldownTurns: 8,
        chance: 0.55,
      }),
    ],
    onHit: [statusEffectOnHit(20, 0xdead0401, { key: "frost", turnsLeft: 2, potency: 1 }, "proc:frozen")],
  },
  specials: ['Casts Frost', 'Self-heals', 'Frost 20%'],
  description: 'A hulking orc draped in fetish charms, breath fogging with stolen winter.',
  lootTable: 'drop:orc_shaman',
});

defineMonster('orc_warchief', {
  name: 'Orc Warchief',
  glyph: 'O',
  color: '#dd6644',
  glow: '#aa3322',
  tags: ['humanoid'],
  tier: 2,
  intelligence: 7,
  packSense: true,
  packRadius: 6,
  hp: 36,
  hpPerLevel: 2.5,
  attack: 4,
  defense: 3,
  damageDice: '2d6',
  sizeClass: 'L',
  massKg: 120,
  resistances: { kinetic: { DR: 6 } },
  speed: 2,
  wielding: ["orc_warchief_maul"],
  equipped: [
    "chain_armor", "helm_steel",
    "gauntlets_iron", "boots_ironshod", "belt_chain",
  ],
  hooks: {
    onBeforeHit: [bonusDamageOnBeforeHit(30, 0xdead0409, 3, "proc:rage")],
    onDamaged: [retaliateOnDamaged(2, "proc:warcry")],
  },
  specials: ["Rage +3 dmg (30%)", "Warcry retaliation", "Warchief maul"],
  description: 'A scarred orc captain in heavy plate. Its war-cry alone can stop a heart.',
  lootTable: 'drop:orc',
});

defineMonster('hobgoblin', {
  name: 'Hobgoblin',
  glyph: 'H',
  color: '#cc8844',
  glow: '#995522',
  tags: ['humanoid'],
  tier: 1,
  minDepth: 9,
  intelligence: 6,
  packSense: true,
  packRadius: 5,
  hp: 28,
  hpPerLevel: 2,
  attack: 3,
  defense: 1,
  damageDice: '1d8',
  sizeClass: 'M',
  massKg: 100,
  resistances: { kinetic: { DR: 3 } },
  speed: 2,
  wielding: [
    "hobgoblin_serrated_warblade",
    "hobgoblin_serrated_warblade",
    "hobgoblin_serrated_warblade",
    "hobgoblin_serrated_warblade",
    "hobgoblin_warblade",
  ],
  equipped: [
    "chain_armor", "helm_iron",
    "gloves_leather", "boots_leather", "belt_leather",
  ],
  hooks: {
    onBeforeHit: [bonusDamageOnBeforeHit(20, 0xdead0402, 3, "proc:rage")],
  },
  specials: ["Rage +3 dmg (20%)", "Serrated warblade", "Fully armored"],
  description: 'A tall, iron-jawed warrior bred for war. Stronger and meaner than any goblin.',
  lootTable: 'drop:hobgoblin',
});

defineMonster('kobold_shaman', {
  name: 'Kobold Shaman',
  glyph: 'k',
  color: '#ffdd44',
  glow: '#ccaa22',
  tags: ['humanoid', 'kobold', 'caster'],
  tier: 0,
  minDepth: 3,
  intelligence: 8,
  visionRange: 9,
  retreatHpPct: 0.30,
  hp: 12,
  hpPerLevel: 1,
  attack: 0,
  defense: 0,
  damageDice: '1d3',
  sizeClass: 'S',
  massKg: 25,
  resistances: { kinetic: { DR: 0 } },
  speed: 2,
  learnedSpellIds: ['lightning'],
  maxMana: 21,
  manaRegen: 0.14,
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'lightning',
        minRange: 2,
        maxRange: 10,
        cooldownTurns: 8,
        chance: 0.65,
      }),
    ],
    onHit: [statusEffectOnHit(25, 0xdead0300, { key: "shock", turnsLeft: 2, potency: 1 }, "proc:shocked")],
  },
  specials: ['Casts Lightning', 'Shock 25%'],
  description: 'A scrawny kobold draped in fraying cloth, crackling with stolen thunder.',
});

defineMonster('druid', {
  name: 'Forest Druid',
  glyph: 'd',
  color: '#66cc44',
  glow: '#339922',
  tags: ['humanoid', 'caster'],
  tier: 1,
  minDepth: 8,
  intelligence: 8,
  visionRange: 9,
  retreatHpPct: 0.25,
  hp: 28,
  hpPerLevel: 2,
  attack: 2,
  defense: 2,
  damageDice: '1d5',
  sizeClass: 'M',
  massKg: 70,
  resistances: {
    kinetic: { DR: 2 },
    chemical: { toxMult: 0.3 },
  },
  speed: 2,
  wielding: ['staff_oak'],
  equipped: ["leather_armor", "sandals_hemp", "belt_leather"],
  learnedSpellIds: ['entangle', 'thorn_burst', 'verdant_ward'],
  maxMana: 40,
  manaRegen: 0.15,
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'verdant_ward',
        abilityId: 'druid_verdant_ward',
        abilityName: 'Verdant Ward',
        targeting: 'self',
        cooldownTurns: 70,
        chance: 0.25,
      }),
      castSpellOnLOS({
        spellId: 'entangle',
        abilityId: 'druid_entangle',
        abilityName: 'Entangle',
        minRange: 2,
        maxRange: 7,
        cooldownTurns: 12,
        chance: 0.55,
      }),
      castSpellOnLOS({
        spellId: 'thorn_burst',
        abilityId: 'druid_thorn_burst',
        abilityName: 'Thorn Burst',
        minRange: 2,
        maxRange: 8,
        cooldownTurns: 6,
        chance: 0.65,
      }),
    ],
  },
  specials: ['Casts Entangle (stun + poison)', 'Casts Thorn Burst (nature + poison 30%)', 'Verdant Ward (regen + stoneskin)'],
  description: 'A robed figure with bark-like skin and eyes like green flame. Thorny vines twist at their command.',
  lootTable: 'drop:caster',
});

defineMonster('dark_acolyte', {
  name: 'Dark Acolyte',
  glyph: 'p',
  color: '#9966cc',
  glow: '#663399',
  tags: ['humanoid', 'caster', 'witchy'],
  tier: 2,
  intelligence: 9,
  visionRange: 9,
  retreatHpPct: 0.25,
  hp: 24,
  hpPerLevel: 1.8,
  attack: 3,
  defense: 2,
  damageDice: '1d6',
  sizeClass: 'M',
  massKg: 65,
  resistances: { kinetic: { DR: 3 } },
  speed: 2,
  wielding: ['staff_oak', 'dagger_quick'],
  equipped: [
    "leather_armor",
    "helm_mage", "scout_hood",
    "sandals_hemp", "boots_leather",
  ],
  learnedSpellIds: ['agony', 'shadow_bolt'],
  maxMana: 45,
  manaRegen: 0.18,
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'agony',
        minRange: 1,
        maxRange: 8,
        cooldownTurns: 10,
        chance: 0.70,
      }),
      castSpellOnLOS({
        spellId: 'shadow_bolt',
        minRange: 2,
        maxRange: 10,
        cooldownTurns: 8,
        chance: 0.50,
      }),
    ],
    onDamaged: [phaseOutOnDamaged(15, 0xdead0408)],
  },
  specials: ['Casts Agony', 'Casts Shadow Bolt', 'Phase out 15%'],
  description: 'A hooded cultist whose whispered curses blister the air itself.',
  lootTable: 'drop:caster',
});

defineMonster('nymph', {
  name: 'Nymph',
  glyph: 'n',
  color: '#88ddaa',
  glow: '#55aa77',
  tags: ['fey', 'humanoid'],
  tier: 0,
  minDepth: 3,
  intelligence: 7,
  aggro: 'passive',
  retreatHpPct: 0.40,
  hp: 12,
  hpPerLevel: 1,
  attack: 1,
  defense: 1,
  damageDice: '1d4',
  sizeClass: 'S',
  massKg: 45,
  resistances: { kinetic: { DR: 0 } },
  speed: 3,
  hooks: {
    onHit: [stealAndBlinkOnHit({ chancePct: 50, seedSalt: 0xdead0030, cooldownTurns: 8, blinkDistance: 10 })],
  },
  specials: ["Steals items", "Teleports away"],
  description: 'A mischievous forest spirit with light fingers and lighter feet.',
  lootTable: 'drop:nymph',
});

defineMonster('marsh_witch', {
  name: 'Marsh Witch',
  glyph: 'W',
  color: '#6aaa78',
  glow: '#3a7a48',
  tags: ['humanoid', 'caster', 'witchy', 'rare', 'overworld'],
  tier: 0,
  rare: true,
  minDepth: 1,
  intelligence: 8,
  hp: 20,
  hpPerLevel: 1.8,
  attack: 1,
  defense: 2,
  damageDice: '1d4',
  sizeClass: 'M',
  massKg: 60,
  resistances: { kinetic: { DR: 0 }, chemical: { toxMult: 0.3 } },
  speed: 2,
  learnedSpellIds: ['bog_curse'],
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'bog_curse',
        abilityId: 'bog_curse',
        abilityName: 'Bog Curse',
        minRange: 1,
        maxRange: 6,
        cooldownTurns: 8,
        chance: 0.3,
      }),
    ],
  },
  specials: ["Casts Bog Curse", "Toxin-resistant"],
  description: 'A crooked figure wreathed in bog mist, muttering fell incantations.',
  lootTable: 'drop:witch',
});

defineMonster('troll', {
  name: 'Troll',
  glyph: 'T',
  color: '#66aa66',
  glow: '#448844',
  tags: ['giant', 'regenerator'],
  tier: 2,
  intelligence: 5,
  hp: 28,
  hpPerLevel: 3,
  attack: 5,
  defense: 1,
  damageDice: '2d6',
  sizeClass: 'L',
  massKg: 200,
  resistances: { kinetic: { DR: 5 }, thermal: { burnMult: 1.5 } },
  speed: 2,
  hooks: {
    onHit: [selfBuffOnHit({ key: "regen", turnsLeft: 3, potency: 2 })],
    onDamaged: [healOnDamaged(30, 0xdead0009, 1, "proc:regenerate")],
  },
  specials: ["Regen buff on hit", "Self-heal 1 HP (30%)"],
  description: 'A hulking regenerator. Weak to fire.',
  lootTable: 'drop:troll',
  corpseEat: { behavior: "devour", cooldownTurns: 10 },
});

defineMonster('ogre', {
  name: 'Ogre',
  glyph: 'O',
  color: '#cc9966',
  glow: '#996633',
  tags: ['giant', 'humanoid'],
  tier: 2,
  intelligence: 5,
  hp: 30,
  hpPerLevel: 2,
  attack: 5,
  defense: 1,
  damageDice: '2d8',
  sizeClass: 'L',
  massKg: 250,
  resistances: { kinetic: { DR: 6 } },
  speed: 2,
  wielding: ["ogre_crushing_club"],
  hooks: null,
  specials: ["Crushing club"],
  description: 'A lumbering slab of muscle and bad intentions.',
  lootTable: 'drop:ogre',
});

defineMonster('demon', {
  name: 'Demon',
  glyph: '&',
  color: '#ff4444',
  glow: '#cc0000',
  tags: ['demon', 'planar'],
  tier: 3,
  intelligence: 8,
  retreatHpPct: 0.20,
  hp: 34,
  hpPerLevel: 4,
  attack: 7,
  defense: 4,
  damageDice: '2d10',
  sizeClass: 'L',
  massKg: 180,
  resistances: {
    kinetic: { DR: 8 },
    thermal: { igniteC: Infinity, burnMult: 0 },
  },
  speed: 2,
  hooks: {
    onHit: [statusEffectOnHit(30, 0xdead000b, { key: "burn", turnsLeft: 4, potency: 3 }, "proc:burning")],
    onDamaged: [retaliateOnDamaged(2, "proc:hellfire")],
  },
  specials: ["Burn 30%", "Hellfire retaliation"],
  description: 'Sulphur and malice given form. Immune to fire.',
  lootTable: 'drop:demon',
});
