// src/content/monsters/special.js
// Aberrations, plants, constructs, and miscellaneous creatures.
import { defineMonster } from '../define.js';
import {
  statusEffectOnHit,
  retaliateOnDamaged,
  slimedOnHit,
  mindflayerBlastOnHit,
} from '../../rules/data/callbacks/combat.js';
import { gazeOnLOS, castSpellOnLOS } from '../../rules/data/callbacks/ai.js';
import { gasSporeExplodeOnDeath } from '../../rules/data/callbacks/death.js';

defineMonster('floating_eye', {
  name: 'Floating Eye',
  glyph: 'e',
  color: '#dd55ff',
  glow: '#9922cc',
  tags: ['aberration', 'psychic'],
  goreType: 'ichor',
  tier: 0,
  minDepth: 4,
  intelligence: 2,
  visionRange: 6,
  ambush: true,
  polymorphResistance: 0.25,
  polymorphStability: 'ordinary',
  hp: 20,
  hpPerLevel: 1.5,
  attack: 1,
  defense: 2,
  damageDice: '1d4',
  sizeClass: 'M',
  massKg: 40,
  resistances: {
    chemical: { toxMult: 0 },
    electric: { ohms: 30 },
  },
  speed: 1,
  hooks: {
    whileLOS: [gazeOnLOS(8)],
    onHit: [mindflayerBlastOnHit(10, 0xdead000e)],
  },
  specials: ["Psychic form can misdirect polymorph"],
  description: 'A pulsing violet eye that drifts in silence. Gaze into it too long and your mind unravels.',
  lootTable: 'drop:floating_eye',
});

defineMonster('mimic', {
  name: 'Mimic',
  glyph: 'M',
  color: '#b07a3f',
  glow: '#7a4d1f',
  tags: ['aberration', 'mimic'],
  goreType: 'ichor',
  tier: 99,
  intelligence: 6,
  ambush: true,
  polymorphResistance: 0.35,
  polymorphStability: 'unstable',
  hp: 16,
  hpPerLevel: 1.5,
  attack: 3,
  defense: 2,
  damageDice: '1d8',
  sizeClass: 'M',
  massKg: 140,
  resistances: { kinetic: { DR: 6 } },
  speed: 2,
  hooks: {
    onHit: [statusEffectOnHit(30, 0xdead0020, { key: "stun", turnsLeft: 2, potency: 1 }, "proc:stunned")],
  },
  specials: ["Adhesive grip (stun 30%)", "Malleable form can bend polymorph off target"],
  description: 'A predatory chest-creature that waits for curious hands.',
  lootTable: 'drop:tier1',
});

defineMonster('stone_taunter', {
  name: 'Taunting Statue',
  glyph: 'G',
  color: '#aaa8a0',
  glow: '#706e66',
  tags: ['construct'],
  goreType: 'spark',
  tier: 99,
  intelligence: 2,
  ambush: true,
  polymorphResistance: 0.8,
  polymorphStability: 'anchored',
  hp: 45,
  hpPerLevel: 0,
  attack: 2,
  defense: 4,
  damageDice: '1d6',
  sizeClass: 'M',
  massKg: 240,
  resistances: {
    kinetic: { DR: 8, bluntMult: 0.7, slashMult: 0.5, pierceMult: 0.4 },
    thermal: { burnMult: 0.6 },
    chemical: { toxMult: 0.2 },
    electric: { ohms: 2400 },
  },
  speed: 2,
  hooks: null,
  specials: ["Strongly resists polymorph"],
  description: 'An animated stone idol that heckles anything that breathes.',
  lootTable: 'drop:stone_taunter',
});

defineMonster('gelatinous_cube', {
  name: 'Gelatinous Cube',
  glyph: '■',
  color: '#55ddbb',
  glow: '#22aa88',
  tags: ['aberration'],
  goreType: 'ichor',
  tier: 0,
  minDepth: 3,
  intelligence: 1,
  hp: 28,
  hpPerLevel: 1.5,
  attack: 1,
  defense: 0,
  damageDice: '1d4',
  sizeClass: 'L',
  massKg: 200,
  resistances: {
    kinetic: { DR: 4 },
    chemical: { toxMult: 0 },
    electric: { ohms: 60 },
  },
  polymorphStability: 'unstable',
  polymorphResistance: 0.2,
  speed: 1,
  hooks: {
    onHit: [
      statusEffectOnHit(30, 0xdead0070, { key: "stun", turnsLeft: 2, potency: 1 }, "proc:stunned"),
      slimedOnHit(40, "proc:slimed"),
    ],
    onDamaged: [retaliateOnDamaged(2, "proc:gelatinous_cube:acid")],
  },
  specials: ["Paralyze 30%", "Acid retaliation (2 dmg)", "Poison/shock resistant", "Unstable polymorph reactions"],
  description: 'A translucent mass of quivering jelly that fills the corridor wall to wall. Bones float inside it.',
});

defineMonster('shrieker', {
  name: 'Shrieker',
  glyph: 'F',
  color: '#e0cc88',
  glow: '#aa9050',
  tags: ['plant'],
  goreType: 'ichor',
  tier: 0,
  minDepth: 3,
  intelligence: 1,
  ambush: true,
  hp: 16,
  hpPerLevel: 1,
  attack: 0,
  defense: 0,
  damageDice: '1d2',
  sizeClass: 'M',
  massKg: 30,
  resistances: { kinetic: { DR: 0 }, chemical: { toxMult: 0 }, thermal: { burnMult: 3.0 } },
  speed: 1,
  learnedSpellIds: ['shrieker_scream'],
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'shrieker_scream',
        abilityId: 'shrieker_scream',
        abilityName: 'Shriek',
        targeting: 'self',
        maxRange: 10,
        cooldownTurns: 12,
        telegraphTurns: 1,
        chance: 0.80,
      }),
    ],
  },
  specials: ["Telegraphed shriek (alerts all nearby monsters)", "Immobile"],
  description: 'A pallid, trumpet-shaped fungus. It has no eyes, no brain — just a scream.',
});

defineMonster('gas_spore', {
  name: 'Gas Spore',
  glyph: 'e',
  color: '#cc66ee',
  glow: '#9933bb',
  tags: ['plant', 'aberration'],
  goreType: 'ichor',
  tier: 0,
  minDepth: 4,
  intelligence: 1,
  canFly: true,
  hp: 4,
  hpPerLevel: 0.5,
  attack: 0,
  defense: 0,
  damageDice: '1d2',
  sizeClass: 'M',
  massKg: 5,
  resistances: { kinetic: { DR: 0 }, thermal: { burnMult: 3.0 } },
  speed: 1,
  hooks: {
    onDeath: [gasSporeExplodeOnDeath({ turnsLeft: 10, tickDamage: 6, radius: 2 })],
  },
  specials: ["Ruptures on death into lingering volatile gas (radius 2, 10 turns)", "Fragile"],
  description: 'A bloated, pulsing sphere that drifts in silence. It looks just like a floating eye — until you pop it.',
});

defineMonster('lichen', {
  name: 'Lichen',
  glyph: 'F',
  color: '#88aa66',
  glow: '#557744',
  tags: ['plant'],
  goreType: 'ichor',
  corpseDropChance: 0.9,
  tier: 0,
  intelligence: 1,
  ambush: true,
  hp: 6,
  hpPerLevel: 0.5,
  attack: 0,
  defense: 0,
  damageDice: '1d2',
  sizeClass: 'XS',
  massKg: 5,
  resistances: { kinetic: { DR: 0 }, chemical: { toxMult: 0.5 }, thermal: { burnMult: 3.0 } },
  speed: 1,
  hooks: null,
  specials: [],
  description: 'A crusty growth clinging to the dungeon stone. Edible, if desperate.',
  lootTable: 'drop:plant',
});
