// src/content/monsters/undead.js
// Undead creatures.
import { defineMonster } from '../define.js';
import {
  statusEffectOnHit,
  drainOnHit,
  healOnDamaged,
  retaliateOnDamaged,
  statusEffectOnDamaged,
  phaseOutOnDamaged,
  drainAndWeakenOnHit,
  bonusDamageIfTargetAfflicted,
} from '../../rules/data/callbacks/combat.js';
import { castSpellOnLOS } from '../../rules/data/callbacks/ai.js';

defineMonster('skeleton_archer', {
  name: 'Skeleton Archer',
  glyph: 's',
  color: '#c8c4b0',
  glow: '#908870',
  tags: ['undead', 'skeletal'],
  goreType: 'none',
  tier: 0,
  minDepth: 3,
  intelligence: 5,
  packSense: true,
  packRadius: 5,
  hp: 10,
  hpPerLevel: 1,
  attack: 3,
  defense: 0,
  damageDice: '1d4',
  sizeClass: 'M',
  massKg: 25,
  resistances: {
    kinetic: { DR: 2, bluntMult: 1.5, pierceMult: 0.5, slashMult: 0.7 },
    chemical: { toxMult: 0 },
  },
  speed: 2,
  hooks: null,
  specials: ['Ranged weapon user (shortbow)'],
  description: 'A rattling skeleton clutching a short bow.',
  lootTable: 'drop:skeleton',
  equipped: ["bow_short", { slot: 'ammo', itemId: 'ammo_arrows' }],
});

defineMonster('skeletal_shadow_caster', {
  name: 'Skeletal Shadow Caster',
  glyph: 's',
  color: '#a088c8',
  glow: '#6a5098',
  tags: ['undead', 'skeletal', 'caster'],
  goreType: 'none',
  tier: 1,
  minDepth: 7,
  intelligence: 9,
  visionRange: 9,
  packSense: true,
  packRadius: 5,
  hp: 16,
  hpPerLevel: 1.4,
  attack: 1,
  defense: 1,
  damageDice: '1d4',
  sizeClass: 'M',
  massKg: 24,
  resistances: {
    kinetic: { DR: 3, bluntMult: 1.5, pierceMult: 0.5, slashMult: 0.7 },
    chemical: { toxMult: 0 },
  },
  speed: 2,
  learnedSpellIds: ['shadow_bolt'],
  maxMana: 36,
  manaRegen: 0.14,
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'shadow_bolt',
        minRange: 2,
        maxRange: 10,
        cooldownTurns: 9,
        chance: 0.6,
      }),
    ],
  },
  specials: ['Casts Shadow Bolt'],
  description: 'A rune-etched skeleton that hurls bolts of abyssal shade from behind the line.',
});

defineMonster('bone_bowman', {
  name: 'Bone Bowman',
  glyph: 's',
  color: '#d8d4c0',
  glow: '#a8a490',
  tags: ['undead', 'skeletal'],
  goreType: 'none',
  tier: 1,
  intelligence: 5,
  packSense: true,
  packRadius: 5,
  hp: 18,
  hpPerLevel: 1.5,
  attack: 3,
  defense: 1,
  damageDice: '1d6',
  sizeClass: 'M',
  massKg: 25,
  resistances: {
    kinetic: { DR: 3, bluntMult: 1.6, pierceMult: 0.6, slashMult: 0.8 },
    chemical: { toxMult: 0 },
  },
  speed: 2,
  hooks: {
    onHit: [statusEffectOnHit(20, 0xdead0020, { key: "bleed", turnsLeft: 3, potency: 1 }, "proc:bleeding")],
  },
  specials: ["Bleed 20%"],
  description: 'A skeletal bowman with practiced aim. Its arrows leave jagged wounds.',
  lootTable: 'drop:skeleton',
  equipped: ["bow_short", { slot: 'ammo', itemId: 'ammo_arrows' }],
});

defineMonster('skeletal_agony_warlock', {
  name: 'Skeletal Agony Warlock',
  glyph: 's',
  color: '#b88ccf',
  glow: '#7a4f9a',
  tags: ['undead', 'skeletal', 'caster', 'warlock'],
  goreType: 'none',
  tier: 0,
  minDepth: 5,
  intelligence: 10,
  visionRange: 9,
  retreatHpPct: 0.25,
  hp: 22,
  hpPerLevel: 1.8,
  attack: 2,
  defense: 2,
  damageDice: '1d6',
  sizeClass: 'M',
  massKg: 26,
  resistances: {
    kinetic: { DR: 2, bluntMult: 1.5, pierceMult: 0.5, slashMult: 0.7 },
    chemical: { toxMult: 0 },
    electric: { ohms: 60 },
  },
  speed: 2,
  learnedSpellIds: ['agony', 'summon_skeleton', 'shadow_bolt'],
  maxMana: 58,
  manaRegen: 0.22,
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: 'summon_skeleton',
        targeting: 'self',
        cooldownTurns: 18,
        chance: 0.35,
        maxAlliesInRadius: 4,
        allyRadius: 7,
      }),
      castSpellOnLOS({
        spellId: 'agony',
        minRange: 1,
        maxRange: 8,
        cooldownTurns: 8,
        chance: 1,
      }),
      castSpellOnLOS({
        spellId: 'shadow_bolt',
        minRange: 1,
        maxRange: 10,
        cooldownTurns: 10,
        chance: 0.45,
      }),
    ],
  },
  specials: ['Casts Agony', 'Summons Skeletons', 'Casts Shadow Bolt'],
  description: 'A black-boned warlock that curses from range and drags fresh skeletons into the fight.',
});

defineMonster('skeleton', {
  name: 'Skeleton',
  glyph: 's',
  color: '#ddd8c8',
  glow: '#aaa590',
  tags: ['undead', 'skeletal'],
  goreType: 'none',
  tier: 1,
  intelligence: 4,
  packSense: true,
  packRadius: 5,
  hp: 16,
  hpPerLevel: 1.8,
  attack: 3,
  defense: 2,
  damageDice: '1d8',
  sizeClass: 'M',
  massKg: 25,
  resistances: {
    kinetic: { DR: 2, bluntMult: 1.5, pierceMult: 0.5, slashMult: 0.7 },
    chemical: { toxMult: 0 },
  },
  speed: 2,
  wielding: [
    'sword_plain', 'sword_plain', 'sword_plain',
    'iron_mace', 'iron_mace',
    'flail',
  ],
  equipped: ["helm_iron", "helm_iron", "leather_armor"],
  hooks: {
    onDamaged: [healOnDamaged(20, 0xdead0008, 2, "proc:reassemble")],
  },
  specials: ["Self-heal 2 HP (20%)", "Wields rusty weapons"],
  description: 'Bones held together by spite. Resistant to piercing but brittle against blunt force.',
  lootTable: 'drop:skeleton',
});

defineMonster('wight', {
  name: 'Wight',
  glyph: 'w',
  color: '#88aacc',
  glow: '#557799',
  tags: ['undead'],
  tier: 1,
  minDepth: 10,
  intelligence: 6,
  packSense: true,
  packRadius: 5,
  hp: 26,
  hpPerLevel: 2,
  attack: 4,
  defense: 2,
  damageDice: '1d8',
  sizeClass: 'M',
  massKg: 60,
  wielding: [
    'sword_plain', 'sword_plain',
    'iron_mace',
    'flail',
  ],
  equipped: ["chain_armor", "leather_armor", "helm_iron"],
  resistances: {
    kinetic: { DR: 3, bluntMult: 1.3, pierceMult: 0.6, slashMult: 0.7 },
    chemical: { toxMult: 0 },
  },
  speed: 2,
  hooks: {
    onHit: [drainAndWeakenOnHit({
      chancePct: 45,
      seedSalt: 0xdead0406,
      divisor: 2,
      cooldownTurns: 3,
      weakenedTurns: 4,
      weakenedPotency: 1,
    })],
  },
  specials: ["Siphon strike (45%, 3-turn cooldown)", "On siphon: drain + weaken"],
  description: 'A revenant in tarnished mail. Its hunger surges in windows, then lashes out with a soul-siphoning grip.',
  lootTable: 'drop:wight',
});

defineMonster('skeletal_marksman', {
  name: 'Skeletal Marksman',
  glyph: 's',
  color: '#e0c8a0',
  glow: '#b89060',
  tags: ['undead', 'skeletal'],
  goreType: 'none',
  tier: 2,
  intelligence: 5,
  packSense: true,
  packRadius: 5,
  hp: 22,
  hpPerLevel: 2,
  attack: 4,
  defense: 2,
  damageDice: '1d8',
  sizeClass: 'M',
  massKg: 28,
  resistances: {
    kinetic: { DR: 6, bluntMult: 1.5, pierceMult: 0.5, slashMult: 0.7 },
    chemical: { toxMult: 0 },
  },
  speed: 2,
  hooks: {
    onHit: [statusEffectOnHit(20, 0xdead0021, { key: "burn", turnsLeft: 3, potency: 2 }, "proc:burning")],
  },
  specials: ["Burn 20%"],
  description: 'A grim skeleton nocking arrows tipped with alchemical fire.',
  lootTable: 'drop:skeleton',
  equipped: ["bow_short", "ammo_fire_arrows"],
});

defineMonster('skeleton_sharpshooter', {
  name: 'Skeleton Sharpshooter',
  glyph: 's',
  color: '#c0bca8',
  glow: '#807c68',
  tags: ['undead', 'skeletal'],
  goreType: 'none',
  tier: 2,
  intelligence: 5,
  packSense: true,
  packRadius: 5,
  hp: 20,
  hpPerLevel: 2,
  attack: 5,
  defense: 3,
  damageDice: '1d6',
  sizeClass: 'M',
  massKg: 25,
  resistances: {
    kinetic: { DR: 6, bluntMult: 1.5, pierceMult: 0.5, slashMult: 0.7 },
    chemical: { toxMult: 0 },
  },
  speed: 2,
  hooks: {
    onHit: [statusEffectOnHit(15, 0xdead0022, { key: "stun", turnsLeft: 1, potency: 1 }, "proc:stunned")],
  },
  specials: ["Stun 15%"],
  description: 'A headless torso that somehow never misses.',
  lootTable: 'drop:skeleton',
  equipped: ["bow_short", { slot: 'ammo', itemId: 'ammo_arrows' }],
});

defineMonster('wraith', {
  name: 'Wraith',
  glyph: 'W',
  color: '#aabbff',
  glow: '#7799dd',
  tags: ['undead', 'spectral'],
  goreType: 'none',
  tier: 2,
  intelligence: 7,
  retreatHpPct: 0.25,
  hp: 24,
  hpPerLevel: 2.5,
  attack: 3,
  defense: 4,
  damageDice: '1d8',
  sizeClass: 'M',
  massKg: 5,
  resistances: {
    kinetic: { DR: 2, bluntMult: 0.3, slashMult: 0.3, pierceMult: 0.3 },
    electric: { ohms: 50 },
  },
  speed: 1,
  hooks: {
    onHit: [drainOnHit(20, 0xdead0003, 3)],
  },
  specials: ["Drain 3 HP (20%)"],
  description: 'A spectral horror. Physical attacks pass through it.',
  lootTable: 'drop:wraith',
});

defineMonster('carrion_shade', {
  name: 'Carrion Shade',
  glyph: 'C',
  color: '#886688',
  glow: '#553355',
  tags: ['undead', 'spectral'],
  goreType: 'none',
  tier: 2,
  intelligence: 7,
  ambush: true,
  retreatHpPct: 0.30,
  hp: 26,
  hpPerLevel: 2.5,
  attack: 3,
  defense: 3,
  damageDice: '1d8',
  sizeClass: 'M',
  massKg: 8,
  resistances: {
    kinetic: { DR: 4, bluntMult: 0.5, slashMult: 0.5, pierceMult: 0.5 },
    chemical: { toxMult: 0 },
  },
  speed: 2,
  hooks: {
    onBeforeHit: [bonusDamageIfTargetAfflicted(3, ["bleed", "poison", "disease", "burn"], "proc:shade_feed")],
    onHit: [
      statusEffectOnHit(30, 0xdead0100, { key: "weakened", turnsLeft: 3, potency: 1 }, "proc:weakened"),
      statusEffectOnHit(20, 0xdead0101, { key: "bleed", turnsLeft: 3, potency: 1 }, "proc:bleeding"),
    ],
    onDamaged: [phaseOutOnDamaged(25, 0xdead0102)],
  },
  specials: ["+dmg vs afflicted", "Weaken 30%", "Bleed 20%", "Phase out 25%"],
  description: 'A shadow that coalesces around old blood. It lurks in darkness and strikes harder against the wounded.',
  lootTable: 'drop:tier2',
  corpseEat: { behavior: "devour", cooldownTurns: 8 },
});

defineMonster('death_archer', {
  name: 'Death Archer',
  glyph: 's',
  color: '#a0a8b0',
  glow: '#6070a0',
  tags: ['undead', 'skeletal'],
  goreType: 'none',
  tier: 3,
  intelligence: 6,
  packSense: true,
  packRadius: 6,
  hp: 28,
  hpPerLevel: 3,
  attack: 5,
  defense: 4,
  damageDice: '2d6',
  sizeClass: 'M',
  massKg: 30,
  resistances: {
    kinetic: { DR: 5, pierceMult: 0.5, slashMult: 0.7 },
    chemical: { toxMult: 0 },
    electric: { ohms: 50 },
  },
  speed: 2,
  learnedSpellIds: ["death_volley"],
  hooks: {
    whileLOS: [
      castSpellOnLOS({
        spellId: "death_volley",
        abilityId: "death_volley",
        abilityName: "Volley",
        minRange: 3,
        maxRange: 10,
        cooldownTurns: 7,
        telegraphTurns: 1,
        chance: 0.55,
      }),
    ],
    onHit: [drainOnHit(20, 0xdead0023, 3)],
  },
  specials: ["Telegraphed volley", "Drain 3 HP (20%)"],
  description: 'An ancient undead marksman wreathed in cold flame. Its arrows sap the life from their targets.',
  lootTable: 'drop:skeleton',
  equipped: ["bow_short", "ammo_fire_arrows"],
});

defineMonster('lich', {
  name: 'Lich',
  glyph: 'L',
  color: '#cc88ff',
  glow: '#9955cc',
  tags: ['undead', 'caster', 'humanoid'],
  goreType: 'none',
  tier: 3,
  intelligence: 10,
  retreatHpPct: 0.25,
  hp: 35,
  hpPerLevel: 3.5,
  attack: 5,
  defense: 5,
  damageDice: '2d6',
  sizeClass: 'M',
  massKg: 40,
  resistances: {
    kinetic: { DR: 4, bluntMult: 0.5, slashMult: 0.5, pierceMult: 0.5 },
    chemical: { toxMult: 0 },
    electric: { ohms: 200 },
  },
  speed: 2,
  wielding: ['staff_oak', 'resonant_quarterstaff'],
  equipped: [
    "leather_armor", "helm_mage",
    "amulet_arcanum", "amulet_focus",
    "ring_arcana", "ring_channeling",
    "boots_leather",
  ],
  hooks: {
    onHit: [drainOnHit(25, 0xdead000c, 2)],
    onDamaged: [statusEffectOnDamaged(20, 0xdead000d, { key: "regen", turnsLeft: 3, potency: 2 }, "proc:phylactery", true)],
  },
  specials: ["Drain 2 HP (25%)", "Phylactery regen (20%)", "Wields arcane staff"],
  description: 'An undead sorcerer sustained by a hidden phylactery.',
  lootTable: 'drop:lich',
});

defineMonster('spectral_snake', {
  name: 'Spectral Snake',
  glyph: 'S',
  color: '#9cc7ff',
  glow: '#5b78c0',
  tags: ['undead', 'spectral', 'beast', 'venomous'],
  goreType: 'none',
  tier: 99,
  rare: true,
  intelligence: 5,
  hp: 6,
  hpPerLevel: 0,
  attack: 4,
  defense: 1,
  damageDice: '1d4+1',
  sizeClass: 'XS',
  massKg: 0.2,
  resistances: {
    kinetic: { DR: 1, bluntMult: 0.7, slashMult: 0.7, pierceMult: 0.5 },
    chemical: { toxMult: 0 },
    thermal: { burnMult: 0.8 },
  },
  speed: 3,
  hooks: {
    onHit: [statusEffectOnHit(40, 0xdead0511, { key: "poison", turnsLeft: 4, potency: 1 }, "proc:poisoned")],
  },
  specials: ["Poison 40%", "Summoned by serpent specters", "Lightning-fast strikes"],
  description: 'A hissing ghost-serpent called from a curse-wrapped hide, striking with supernatural speed.',
});
