import { S_RING, S_AMULET } from '../base.js';

export const rings = {
  ring_health:    { glyph:"◌", fg:"#ffb347", glow:"#ffb347", baseScale: S_RING },
  ring_precision: { glyph:"◌", fg:"#b3e6ff", glow:"#b3e6ff", baseScale: S_RING },
  ring_arcana:    { glyph:"◌", fg:"#a480ff", glow:"#a480ff", baseScale: S_RING },
  ring_fire_resist:   { glyph:"◌", fg:"#ff9a5c", glow:"#ff6f2e", baseScale: S_RING },
  ring_poison_resist: { glyph:"◌", fg:"#9bdc7a", glow:"#6ca84f", baseScale: S_RING },
  ring_endurance:     { glyph:"◌", fg:"#f0cf7c", glow:"#c8a658", baseScale: S_RING },
  ring_sorcery:       { glyph:"◌", fg:"#9f8dff", glow:"#7360cf", baseScale: S_RING },
  ring_channeling:    { glyph:"◌", fg:"#7fd3ff", glow:"#4b9bc7", baseScale: S_RING },
  ring_of_fury:       { glyph:"◌", fg:"#ff7c6e", glow:"#cf4a3f", baseScale: S_RING },
  serpent_ring:       { glyph:"◌", fg:"#7cc46b", glow:"#4d8f41", baseScale: S_RING },
  brawler_band:       { glyph:"◌", fg:"#d0a272", glow:"#9b7246", baseScale: S_RING },
  amulet_guarded:      { glyph:"\"", fg:"#d5d9de", glow:"#9ba4af", baseScale: S_AMULET },
  amulet_hearthwire:   { glyph:"\"", fg:"#d89f6d", glow:"#9c6c46", baseScale: S_AMULET },
  amulet_vigor:        { glyph:"\"", fg:"#f1c36c", glow:"#ba8f3f", baseScale: S_AMULET },
  amulet_warding:      { glyph:"\"", fg:"#c7d4e3", glow:"#8fa0b2", baseScale: S_AMULET },
  amulet_focus:        { glyph:"\"", fg:"#9fc7ff", glow:"#6c91c9", baseScale: S_AMULET },
  pendant_soulkeeper:  { glyph:"\"", fg:"#f2a96f", glow:"#c57844", baseScale: S_AMULET },
  pendant_stormward:   { glyph:"\"", fg:"#8fd0f2", glow:"#5d97b7", baseScale: S_AMULET },
  amulet_lifeblood:    { glyph:"\"", fg:"#ff8a83", glow:"#c95a54", baseScale: S_AMULET },
  amulet_arcanum:      { glyph:"\"", fg:"#b08fff", glow:"#7d62c9", baseScale: S_AMULET },
  // Cursed rings
  ring_copper:      { glyph:"◌", fg:"#c87a3a", glow:"#8a5020", baseScale: S_RING },
  ring_bone:        { glyph:"◌", fg:"#d8d0c0", glow:"#a8a090", baseScale: S_RING },
  ring_hunger:      { glyph:"◌", fg:"#aa8844", glow:"#775522", baseScale: S_RING },
  ring_fumbling:    { glyph:"◌", fg:"#bb9966", glow:"#886633", baseScale: S_RING },
  ring_weakness:    { glyph:"◌", fg:"#99887a", glow:"#665544", baseScale: S_RING },
  ring_blindness:   { glyph:"◌", fg:"#555566", glow:"#333344", baseScale: S_RING },
  ring_teleportation: { glyph:"◌", fg:"#66eeff", glow:"#33bbcc", baseScale: S_RING },
  ring_fragility:   { glyph:"◌", fg:"#cc9999", glow:"#996666", baseScale: S_RING },
  ring_mana_drain:  { glyph:"◌", fg:"#7766aa", glow:"#4a3a77", baseScale: S_RING },
  ring_ironwill:    { glyph:"◌", fg:"#b0bcc8", glow:"#7a8694", baseScale: S_RING },
  ring_fateweaver:  { glyph:"◌", fg:"#d4a8e0", glow:"#a070b8", baseScale: S_RING },
  ring_voidchannel: { glyph:"◌", fg:"#6a5a8a", glow:"#3a2a5a", baseScale: S_RING },
  // Cursed amulets
  amulet_strangulation: { glyph:"\"", fg:"#aa4444", glow:"#772222", baseScale: S_AMULET },
  amulet_aggravation:   { glyph:"\"", fg:"#dd6644", glow:"#aa3322", baseScale: S_AMULET },
  pendulum_of_three_tolls: { glyph:"\"", fg:"#8a72b6", glow:"#5f4a85", baseScale: S_AMULET },
  tithekeeper_choker:      { glyph:"\"", fg:"#c98a6b", glow:"#8d5b41", baseScale: S_AMULET },
  eclipse_torc:            { glyph:"\"", fg:"#cfba7a", glow:"#8f7a45", baseScale: S_AMULET },
  // Missing rings
  ring_conflict:           { glyph:"◌", fg:"#dd5544", glow:"#aa2222", baseScale: S_RING },
  bloodward_signet:        { glyph:"◌", fg:"#c86060", glow:"#8a3030", baseScale: S_RING },
  // Missing amulets
  pendant_lucky:           { glyph:"\"", fg:"#e8d46a", glow:"#b8a44a", baseScale: S_AMULET },
  echo_pendant:            { glyph:"\"", fg:"#7ab0d8", glow:"#4a7aa0", baseScale: S_AMULET },
  deathascendant_medallion: { glyph:"\"", fg:"#c86a8a", glow:"#8a3a5a", baseScale: S_AMULET },
};
