import { S_WEAPON_S, S_WEAPON_M, S_WEAPON_L } from '../base.js';

export const weapons = {
  sword_plain:        { glyph:")",  fg:"#e8e2b0", glow:"#e8e2b0", baseScale: S_WEAPON_M },
  dagger_quick:       { glyph:")",  fg:"#f7d794", glow:"#f7d794", baseScale: S_WEAPON_S },
  axe_heavy:          { glyph:")",  fg:"#e0c070", glow:"#e0c070", baseScale: S_WEAPON_M },
  bow_short:          { glyph:"}",  fg:"#c4a46c", glow:"#a08050", baseScale: S_WEAPON_L },
  bow_recurve:        { glyph:"}",  fg:"#c8b37a", glow:"#8b7245", baseScale: S_WEAPON_L },
  bow_long:           { glyph:"}",  fg:"#b09060", glow:"#887050", baseScale: S_WEAPON_L },
  bow_flaming:        { glyph:"}",  fg:"#ff8a3c", glow:"#ff4a1f", baseScale: S_WEAPON_L },
  bow_composite:      { glyph:"}",  fg:"#d4a8e0", glow:"#a070b8", baseScale: S_WEAPON_L },
  bow_shadow:         { glyph:"}",  fg:"#7088cc", glow:"#4060a8", baseScale: S_WEAPON_L },
  bow_mirror:         { glyph:"}",  fg:"#d0d8e8", glow:"#a0a8b8", baseScale: S_WEAPON_L },
  longsword:          { glyph:"/",  fg:"#c8cce0", glow:"#9098b8", baseScale: S_WEAPON_M },
  iron_mace:          { glyph:")",  fg:"#9090a0", glow:"#707080", baseScale: S_WEAPON_M },
  morningstar:        {
    glyph: ")",
    fg: "#c5bebe",
    glow: "#aaaaaa",
    baseScale: S_WEAPON_M,
    layers: [
      { glyph: ")", fg: "#4e2c2c", glow: "#aaaaaa", dx: 0.04, dy: 0.2 },
      { glyph: "*", fg: "#c5bebe", glow: "#aaaaaa", dx: -0.04, dy: -0.02 },
    ]
  },
  warhammer:          { glyph:"T",  fg:"#a8a0b8", glow:"#706880", baseScale: S_WEAPON_L },
  flail:              { glyph:")",  fg:"#a59aa8", glow:"#746b80", baseScale: S_WEAPON_M },
  venomfang_dagger:   { glyph:")",  fg:"#98e070", glow:"#63c44c", baseScale: S_WEAPON_S },
  venomfang:          { glyph:")",  fg:"#98e070", glow:"#63c44c", baseScale: S_WEAPON_S },
  nightfang_dagger:   { glyph:")",  fg:"#8df0a8", glow:"#52d57a", baseScale: S_WEAPON_S },
  nightfang:          { glyph:")",  fg:"#8df0a8", glow:"#52d57a", baseScale: S_WEAPON_S },
  caustic_stiletto:   { glyph:"/",  fg:"#a0cc40", glow:"#70a020", baseScale: S_WEAPON_S },
  stormtouched_mace:  { glyph:")",  fg:"#8090e0", glow:"#4060cc", baseScale: S_WEAPON_M },
  sparking_knife:     { glyph:")",  fg:"#9cc7ff", glow:"#6da2f5", baseScale: S_WEAPON_S },
  smoldering_club:    { glyph:")",  fg:"#cf8b4e", glow:"#a65f2d", baseScale: S_WEAPON_M },
  chipped_fang:       { glyph:")",  fg:"#d2bf95", glow:"#9b865f", baseScale: S_WEAPON_S },
  leech_blade:        { glyph:"/",  fg:"#b95a6e", glow:"#8f3a50", baseScale: S_WEAPON_M },
  warhammer_of_fury:  { glyph:"T",  fg:"#c09a7a", glow:"#8d6b4f", baseScale: S_WEAPON_L },
  pyreheart_mace:     { glyph:")",  fg:"#e77a41", glow:"#bb4c1d", baseScale: S_WEAPON_M },
  witchfire_sword:    { glyph:"/",  fg:"#d672ff", glow:"#9a42c7", baseScale: S_WEAPON_M },
  howling_maul:       { glyph:"T",  fg:"#9aa4b8", glow:"#6a7487", baseScale: S_WEAPON_L },
  glacial_edge:       { glyph:"/",  fg:"#8cc9ff", glow:"#4f8fc4", baseScale: S_WEAPON_M },
  soulreaver_axe:     { glyph:")",  fg:"#d45f8e", glow:"#9d3e68", baseScale: S_WEAPON_M },
  stormcaller_blade:  { glyph:"/",  fg:"#7fb4ff", glow:"#4f79d1", baseScale: S_WEAPON_M },
  staff_oak:          { glyph:"/",  fg:"#b88a5a", glow:"#835f3d", baseScale: S_WEAPON_L },
  ember_knife:        { glyph:")",  fg:"#ff8830", glow:"#ff5500", baseScale: S_WEAPON_S },
  flametongue:        { glyph:"/",  fg:"#ff6020", glow:"#ff3300", baseScale: S_WEAPON_M },
  ashen_reaver:       { glyph:"/",  fg:"#cc3000", glow:"#ff4400", baseScale: S_WEAPON_M },
  predator_stakebow:  { glyph:"}",  fg:"#9bcf68", glow:"#67943c", baseScale: S_WEAPON_L },
  doom_crossbow:      { glyph:"}",  fg:"#7f6aa8", glow:"#524079", baseScale: S_WEAPON_L },
  resonant_quarterstaff: { glyph:"/", fg:"#6eb7de", glow:"#3e7f9f", baseScale: S_WEAPON_L },
  venom_kris:         { glyph:")",  fg:"#8adf6c", glow:"#56a640", baseScale: S_WEAPON_S },
  never_sated_warclub:{ glyph:"T",  fg:"#b08f62", glow:"#7a5f3f", baseScale: S_WEAPON_L },
  blood_covenant_rapier: { glyph:"/", fg:"#d06c6c", glow:"#9a3f3f", baseScale: S_WEAPON_M },
  cataclysm_warspear: { glyph:"/",  fg:"#c9b27e", glow:"#8e774c", baseScale: S_WEAPON_L },
  sunsword:           { glyph:"/",  fg:"#ffffff", glow:"#ffe8a0", baseScale: S_WEAPON_M },
};
