import "../../src/content/items/dawnbreaker.js";
import "../../src/content/items/weapons.js";
import "../../src/content/items/rangedWeapons.js";
import "../../src/content/items/armors.js";
import "../../src/content/items/helms.js";
import "../../src/content/items/belts.js";
import "../../src/content/items/gloves.js";
import "../../src/content/items/legs.js";
import "../../src/content/items/boots.js";
import "../../src/content/items/rings.js";
import "../../src/content/items/necks.js";
import "../../src/content/items/offhands.js";
import "../../src/content/items/potions.js";
import "../../src/content/items/spellbooks.js";
import "../../src/content/items/scrolls.js";
import "../../src/content/items/wands.js";
import "../../src/content/items/economy.js";
import "../../src/content/items/lodbrokSerpentBoundBreeches.js";
import "../../src/content/items/potionOfRadiance.js";
import "../../src/content/items/sunVessel.js";
import "../../src/content/items/sunsword.js";
import "../../src/content/items/fishingRod.js";
import "../../src/content/monsters/barrowWight.js";
import { installContent } from "../../src/content/install.js";

installContent();
